### PR TITLE
updated package.json depencies, created bash script

### PR DESCRIPTION
**Pull request by icarlosmendez**
Cleaned up duplicate dependencies in package.json. No more warnings during `npm install`. Also wrote bash script to handle the database refresh workflow. If this code base lives on this will be helpful to future devs.

### CODE REVIEW

**Comment by icarlosmendez** [comment]
Chris,
Will you review the package.json just to make sure that the correct packages are in the dependencies list versus the devDependencies. I adjusted them based on my understanding but a second pair of eyes never hurts.

**Comment by reactivepixel** [comment]
Sure thing Carlos, Ill be going though in a few days. Feel free to make any adjustments you see fit in 1 pull request, I'll sort through it all coming up. :)

**Comment by icarlosmendez** [comment]
Developing route tests using a new node module called 'Supertest' which works with Mocha and Chai. I am experiencing a problem though in my local dev environment, the server seems like it won't keep running. Therefore I don't know if my test failures are from that or just because they aren't written properly.

**Comment by reactivepixel** [comment]
rerouting this merge into the v1 codebase

**Comment by brandonbrown** [comment]
Hello!

 

You have a new message, please read <http://video-makers.ru/bulb.php?z0r>

 

brandon@bybrandonbrown.com

**Comment by brandonbrown** [comment]
Hello!

 

You have a new message, please read <http://acwbc.com/have.php?2mxk>

 

brandon@bybrandonbrown.com

**Comment by brandonbrown** [comment]
Hi,

I guess you are interested in that stuff, here is a useful link <http://nucrogezu.southcarolinadreams.com/lnnivr>

Hugs, brandon@bybrandonbrown.com

**Pull request closed without merging**
